nodeLinker: node-modules

packageExtensions:
  "@angular-builders/jest@*":
    dependencies:
      jest-preset-angular: "*"
      ts-jest: "*"
    peerDependencies:
      "@angular/core": "*"
      "@angular/platform-browser-dynamic": "*"
      typescript: "*"
  jest-preset-angular@*:
    peerDependencies:
      typescript: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-berry.js
