yarnPath: ".yarn/releases/yarn-berry.js"
nodeLinker: node-modules
packageExtensions:
  "@angular-builders/jest@*":
    dependencies:
      "jest-preset-angular": "*"
      "ts-jest": "*"
    peerDependencies:
      "@angular/core": "*"
      "@angular/platform-browser-dynamic": "*"
      "typescript": "*"
  "jest-preset-angular@*":
    peerDependencies:
      "typescript": "*"
